# application.yml
spring:
  application:
    name: form-submission-service
  
  datasource:
    url: jdbc:h2:mem:testdb  # For development - change to your database
    # url: jdbc:mysql://localhost:3306/form_submissions
    # url: jdbc:postgresql://localhost:5432/form_submissions
    driver-class-name: org.h2.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: org.postgresql.Driver
    username: sa
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'validate' or 'none' for production
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        
  h2:
    console:
      enabled: true  # Only for development
      path: /h2-console
      
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# Google Sheets 配置
google:
  sheets:
    spreadsheet-id: 18ea2cQeXOt96dGbssCP_ynsTP5AHEmQpFXE48-PtToo
    worksheet-name: Sheet1
    auto-sync: true  # 是否自动同步新提交到 Google Sheets
    batch-size: 100  # 批量同步时的批次大小
    
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,google-sheets
  endpoint:
    health:
      show-details: always

---
# application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/form_submissions}
    username: ${DATABASE_USERNAME:your_username}
    password: ${DATABASE_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  h2:
    console:
      enabled: false
      
logging:
  level:
    com.example: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN